//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjectNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intership
    {
        public int IntershipID { get; set; }
        public Nullable<int> Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
